#-*- makefile -*-

#
# bwa makefile rules
# 

MAKEDIR = $(dir $(lastword $(MAKEFILE_LIST)))
ifeq ($(findstring Makefile.ngsvars,$(MAKEFILE_LIST)),)
include $(MAKEDIR)Makefile.ngsvars
endif
ifeq ($(findstring Makefile.samtools,$(MAKEFILE_LIST)),)
include $(MAKEDIR)Makefile.samtools
endif

# bwa
ifndef BWA
BWA=bwa
endif
ifndef BWA_THREADS
BWA_THREADS=$(THREADS)
endif
ifndef BWA_OPTIONS
BWA_OPTIONS=-t $(BWA_THREADS)
endif
ifndef BWA_REF
BWA_REF=$(REF)
endif

%.bam: %$(READ1_LABEL).fastq.gz %$(READ2_LABEL).fastq.gz
	$(BWA) mem $(BWA_OPTIONS) $(BWA_REF) $^ | $(SAMTOOLS) view -Sbh - > $@.tmp && mv $@.tmp $@

##############################
# settings
##############################
.PHONY: bwa-settings bwa-header

print-%:
	@echo '$*=$($*)'

bwa-header:
	@echo -e "\nMakefile.bwa options"
	@echo "===================="


bwa-settings: bwa-header print-BWA print-BWA_THREADS print-BWA_OPTIONS print-BWA_REF
