#-*- makefile -*-

# General rules

# Make: make sure to use version >= 3.82
ifndef MAKE
MAKE=make
endif

# Utility programs
ifndef AWK
AWK=awk
endif
ifndef CAT
CAT=cat
endif
ifndef ZCAT
ZCAT=zcat
endif
ifndef GREP
GREP=grep
endif
ifndef GZIP
GZIP=gzip
GZIP_OPTIONS=
endif

##############################
# sbatch submission
##############################
ifndef SBATCH
SBATCH=sbatch
endif
ifndef SBATCH_OPTIONS
SBATCH_OPTIONS=
endif

##############################
# SLURM options
##############################
# SLURM account empty - required in calling Makefile
ifndef SLURM_ACCOUNT
SLURM_ACCOUNT=
endif
# SLURM time - 1h default
ifndef SLURM_TIME
SLURM_TIME=01:00:00
endif
# SLURM N nodes
ifndef SLURM_N_NODES
SLURM_N_NODES=1
endif
# Extra header info. Put everything in variable.
ifndef SLURM_EXTRA_HEADER
SLURM_EXTRA_HEADER=
endif
# Stuff to be inserted before command
ifndef SLURM_PREHOOK
SLURM_PREHOOK=
#="module load samtools\n\
#module load bwa\n\
#"
endif

# Jobname variable
ifndef SLURM_JOBNAME
SLURM_JOBNAME=
endif
# Logging
ifndef SLURM_OUT
SLURM_OUT=
endif
ifndef SLURM_ERR
SLURM_ERR=
endif
# Workdir variable
ifndef SLURM_WORKDIR
SLURM_WORKDIR=
endif

# username - there must be an easier way to get this info
ifndef SLURM_USER
$(eval SLURM_USER=$(shell echo $$USER))
endif
# Mailtype variable
ifndef SLURM_MAILTYPE
SLURM_MAILTYPE=All
endif
# Mailuser variable
ifndef SLURM_PARTITION
SLURM_PARTITION=devel
endif
# Partition
ifndef SLURM_MAILUSER
SLURM_MAILUSER=
endif
# SLURM n cores
ifndef SLURM_N_CORES
SLURM_N_CORES=8
ifeq ($(SLURM_PARTITION),core)
SLURM_N_CORES=1
endif
endif
# SLURM command
ifndef SLURM_COMMAND
SLURM_COMMAND=
endif
# SLURM make_j option: number of parallel processes - not necessarily
# same as number of cores
ifndef SLURM_MAKE_J
SLURM_MAKE_J=1
endif
# SLURM_MODULES: list of modules to load
ifndef SLURM_MODULES
SLURM_MODULES=
endif

# extra output suffix = .sh so this rule is always run
%.sbatch:
ifeq ($(SLURM_ACCOUNT),)
	echo -e No SLURM_ACCOUNT defined; exiting!
else
	echo -e "#!/bin/bash -l" > $@.sh 
	echo -e "#SBATCH" -p $(SLURM_PARTITION) >> $@.sh 
ifeq ($(SLURM_PARTITION),halvan)
	echo -e "#SBATCH" -M $(SLURM_PARTITION) >> $@.sh
endif
	echo -e "#SBATCH" -A $(SLURM_ACCOUNT) >> $@.sh 
	echo -e "#SBATCH" -n $(SLURM_N_CORES) >> $@.sh 
ifeq ($(SLURM_PARTITION),node)
	echo -e "#SBATCH" -N $(SLURM_N_NODES) >> $@.sh 
endif
	echo -e "#SBATCH" -t $(SLURM_TIME) >> $@.sh 
ifneq ($(SLURM_JOBNAME),)
	echo -e "#SBATCH" -J $(SLURM_JOBNAME) >> $@.sh 
else
	echo -e "#SBATCH" -J $* >> $@.sh 
endif
ifneq ($(SLURM_OUT),)
	echo -e "#SBATCH" -o $(SLURM_OUT) >> $@.sh
endif
ifneq ($(SLURM_ERR),)
	echo -e "#SBATCH" -e $(SLURM_ERR) >> $@.sh
endif
ifneq ($(SLURM_WORKDIR),)
	echo -e "#SBATCH" -D $(SLURM_WORKDIR) >> $@.sh
endif
ifneq ($(SLURM_EXTRA_HEADER),)
	echo -e $(SLURM_EXTRA_HEADER) >> $@.sh 
endif
	echo -e "#SBATCH --mail-type="$(SLURM_MAILTYPE) >> $@.sh
ifneq ($(SLURM_MAILUSER),)
	echo -e "#SBATCH --mail-user="$(SLURM_MAILUSER) >> $@.sh
endif
	echo -e "\n\n#" `date` >> $@.sh 
ifneq ($(SLURM_MODULES),)
	echo -e $(addsuffix "\n", $(addprefix "module load ",$(SLURM_MODULES))) >> $@.sh
endif
	echo -e "\n\n"$(SLURM_PREHOOK) >> $@.sh
ifneq ($(SLURM_COMMAND),)
	echo -e $(SLURM_COMMAND) >> $@.sh
else
	echo -e $(MAKE) -j $(SLURM_MAKE_J) $*.log >> $@.sh
endif
	$(SBATCH) $(SBATCH_OPTIONS) $@.sh
endif

#JOB=`sbatch --output=/dev/null --error=/dev/null $@ $BS 2>&1 | egrep -o -e "\b[0-9]+$"`

# logging - output suffix = .runlog so this rule is always run
%.log:
	echo -e "\n\n"`date`"\n\n" >> $@.tmp
	$(MAKE) $(MFLAGS) $* 2>&1 | tee -a $@.tmp && mv $@.tmp $*.runlog


# Want %.log to run every time but this doesn't help?!?
.PHONY: general-settings general-header

# http://blog.melski.net/2010/11/30/makefile-hacks-print-the-value-of-any-variable/
print-%:
	@echo '$*=$($*)'

general-settings: general-header print-AWK print-CAT print-ZCAT print-GREP print-GZIP print-GZIP_OPTIONS print-SBATCH print-SBATCH_OPTIONS general-slurm-header print-SLURM_PARTITION print-SLURM_N_CORES print-SLURM_N_NODES print-SLURM_ACCOUNT print-SLURM_WORKDIR print-SLURM_USER print-SLURM_MAILUSER print-SLURM_MAILTYPE print-SLURM_TIME print-SLURM_JOBNAME print-SLURM_OUT print-SLURM_ERR print-SLURM_MODULES print-SLURM_MAKE_J print-SLURM_EXTRA_HEADER print-SLURM_PREHOOK

general-header:
	@echo -e "\nMakefile.general options"
	@echo "========================"


general-slurm-header:
	@echo -e "\nSLURM settings"
	@echo "------------------------"
