#-*- makefile -*-

MAKEDIR = $(dir $(lastword $(MAKEFILE_LIST)))
ifeq ($(findstring Makefile.ngsvars,$(MAKEFILE_LIST)),)
include $(MAKEDIR)Makefile.ngsvars
endif
#
# variation analysis makefile rules
# 

# vcftools
ifndef VCFTOOLS
VCFTOOLS_HOME=.
endif
ifndef VCFTOOLS_OPTIONS
VCFTOOLS_OPTIONS=
endif
ifndef VCFTOOLS_STATS_OPTIONS
VCFTOOLS_STATS_OPTIONS=
endif

# htslib
ifndef HTSLIB_HOME
HTSLIB_HOME=.
endif
ifndef VCF_HOME
VCF_HOME=.
endif

%.ped: %.vcf
	$(VCFTOOLS_HOME)/vcftools $(VCFTOOLS_OPTIONS) --vcf $< --plink --out $*.tmp && mv $*.tmp.ped $@; mv $*.tmp.map $*.map

%.stats.dump: %.vcf
	$(VCFTOOLS_HOME)/vcf-stats $(VCFTOOLS_STATS_OPTIONS)  $< -p $*.stats

%.frq: %.vcf
	$(VCFTOOLS_HOME)/vcftools --freq $(VCFTOOLS_OPTIONS) --vcf  $< --out $*.tmp && rename $*.tmp  $* $**

%.2.frq: %.vcf
	$(VCFTOOLS_HOME)/vcftools --counts --freq2 $(VCFTOOLS_OPTIONS) --vcf  $< --out $*.2.tmp && rename $*.2.tmp  $*.2 $**

%.chk: %.vcf
	$(VCF_HOME)/vcf check $< > $@.tmp && mv $@.tmp $@

%-summary.pdf: %.chk
	$(HTSLIB_HOME)/misc/plot-vcfcheck $< -p $*

##############################
# snpeff
##############################
ifndef SNPEFF_HOME
SNPEFF_HOME=.
endif
ifndef SNPEFF_CONFIG
SNPEFF_CONFIG=$(SNPEFF_HOME)/snpEff.config
endif
ifndef SNPEFF_OPTIONS
SNPEFF_OPTIONS=-c $(SNPEFF_CONFIG) -o gatk
endif
ifndef SNPEFF_GENOME_VERSION
SNPEFF_GENOME_VERSION=hg19
endif
ifndef SNPEFF_JAVA_MEM
SNPEFF_JAVA_MEM=$(JAVA_MEM)
endif
ifndef SNPEFF_JAR
SNPEFF_JAR=$(SNPEFF_HOME)/snpEff.jar
endif
ifndef SNPEFF_JAVA_TMPDIR
SNPEFF_JAVA_TMPDIR=$(JAVA_TMPDIR)
endif
ifndef SNPEFF_COMMAND
SNPEFF_COMMAND=java -Xmx$(SNPEFF_JAVA_MEM) -Djava.io.tmpdir=$(SNPEFF_JAVA_TMPDIR) -jar $(SNPEFF_JAR)
endif
ifndef SNPEFF_DBLIST
SNPEFF_DBLIST=hg19
endif
# DB targets
SNPEFF_DBLIST_TARGETS:=$(addprefix snpeff-download-,$(SNPEFF_DBLIST))

snpeff-download-%:
	cd $(SNPEFF_HOME) && java -jar $(SNPEFF_JAR) download $*

%.annotated.vcf: %.vcf
	$(SNPEFF_COMMAND) $(SNPEFF_OPTIONS) $(SNPEFF_GENOME_VERSION) $< > $@.tmp && mv $@.tmp $@

##############################
# annovar
##############################
ifndef ANNOVAR_HOME
ANNOVAR_HOME=.
endif
ifndef ANNOVAR_OPTIONS
ANNOVAR_OPTIONS=
endif
ifndef ANNOVAR_DB
ANNOVAR_DB=$(ANNOVAR_HOME)/humandb
endif
ifndef ANNOVAR_BUILDVER
ANNOVAR_BUILDVER=hg19
endif
ifndef ANNOVAR_DBLIST
ANNOVAR_DBLIST=dgv genomicSuperDups gwascatalog tfbs wgEncodeRegTfbsClustered wgEncodeRegDnaseClustered phastConsElements46way
endif
ifndef ANNOVAR_DBLIST_WEBFROM_ANNOVAR
ANNOVAR_DBLIST_WEBFROM_ANNOVAR=1000g2012apr cosmic64 esp6500si_all esp6500si_ea ljb_all snp137 refGene avsift
endif

annovar-download-webfrom-annovar-%:
	$(ANNOVAR_HOME)/annotate_variation.pl -buildver $(ANNOVAR_BUILDVER) -downdb -webfrom annovar $* $(ANNOVAR_DB)

annovar-download-%:
	$(ANNOVAR_HOME)/annotate_variation.pl -buildver $(ANNOVAR_BUILDVER) -downdb $* $(ANNOVAR_DB)

# DB targets
ANNOVAR_DBLIST_TARGETS:=$(addprefix annovar-download-,$(ANNOVAR_DBLIST))
ANNOVAR_DBLIST_WEBFROM_ANNOVAR_TARGETS:=$(addprefix annovar-download-webfrom-annovar-,$(ANNOVAR_DBLIST_WEBFROM_ANNOVAR))

# Rule for setting up db
# NB: this rule is problematic in that it is always run. We need a
# list of all output database file names as targets.
annovar-setupdb: $(ANNOVAR_DBLIST_TARGETS) $(ANNOVAR_DBLIST_WEBFROM_ANNOVAR_TARGETS)

ifndef ANNOVAR_TABLE_OPTIONS
ANNOVAR_TABLE_OPTIONS=--otherinfo
endif
%.avinput.hg19_multianno.txt: %.avinput
	$(ANNOVAR_HOME)/table_annovar.pl $< $(ANNOVAR_DB) $(ANNOVAR_TABLE_OPTIONS) --buildver hg19

ifndef ANNOVAR_CONVERT_OPTIONS
ANNOVAR_CONVERT_OPTIONS=--includeinfo
endif
ifndef ANNOVAR_CONVERT_VCF_FORMAT
ANNOVAR_CONVERT_VCF_FORMAT=vcf4
endif
%.avinput: %.vcf
	$(ANNOVAR_HOME)/convert2annovar.pl  $(ANNOVAR_OPTIONS) $(ANNOVAR_CONVERT_OPTIONS) -format $(ANNOVAR_CONVERT_VCF_FORMAT) $< > $@.tmp && mv $@.tmp $@


##############################
# Settings
##############################
print-%:
	@echo '$*=$($*)'

variation-header:
	@echo -e "\nMakefile.variation options"
	@echo "============================"

vcftools-header:
	@echo -e "\nvcftools options"
	@echo "--------------------"

annovar-header:
	@echo -e "\nannovar options"
	@echo "--------------------"

snpeff-header:
	@echo -e "\nsnpeff options"
	@echo "--------------------"

variation-settings: variation-header vcftools-header print-VCFTOOLS_HOME print-VCFTOOLS_OPTIONS print-VCFTOOLS_STATS_OPTIONS print-HTSLIB_HOME print-VCF_HOME snpeff-header print-SNPEFF_HOME print-SNPEFF_CONFIG print-SNPEFF_OPTIONS print-SNPEFF_GENOME_VERSION print-SNPEFF_JAVA_MEM print-SNPEFF_JAR print-SNPEFF_JAVA_TMPDIR print-SNPEFF_COMMAND print-SNPEFF_DBLIST annovar-header print-ANNOVAR_HOME print-ANNOVAR_OPTIONS print-ANNOVAR_DB print-ANNOVAR_BUILDVER print-ANNOVAR_DBLIST print-ANNOVAR_DBLIST_WEBFROM_ANNOVAR print-ANNOVAR_DBLIST_TARGETS print-ANNOVAR_DBLIST_WEBFROM_ANNOVAR_TARGETS print-ANNOVAR_TABLE_OPTIONS print-ANNOVAR_CONVERT_OPTIONS

