#-*- makefile -*-
#
# File: Makefile.sequenceprocessing
#
# Description: recipies for various sequence processing
#
MAKEDIR = $(dir $(lastword $(MAKEFILE_LIST)))
ifeq ($(findstring Makefile.ngsvars,$(MAKEFILE_LIST)),)
include $(MAKEDIR)Makefile.ngsvars
endif

##################################################
# Cutadapt and resyncmates
##################################################
# cutadapt
ifndef CUTADAPT
CUTADAPT=cutadapt
endif
ifndef CUTADAPT_THREEPRIME
CUTADAPT_THREEPRIME=AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC
endif
ifndef CUTADAPT_FIVEPRIME
CUTADAPT_FIVEPRIME=AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT
endif
ifndef CUTADAPT_OPTIONS
CUTADAPT_OPTIONS=
endif

%$(READ1_LABEL).trimmed.fastq.gz: %$(READ1_LABEL).fastq.gz
	$(CUTADAPT) $(CUTADAPT_OPTIONS) -a $(CUTADAPT_THREEPRIME) $< -o $(@:.gz=).tmp.gz > $*.cutadapt_metrics && mv $(@:.gz=).tmp.gz $@

%$(READ2_LABEL).trimmed.fastq.gz: %$(READ2_LABEL).fastq.gz
	$(CUTADAPT) $(CUTADAPT_OPTIONS) -a $(CUTADAPT_FIVEPRIME) $< -o $(@:.gz=).tmp.gz > $*.cutadapt_metrics && mv $(@:.gz=).tmp.gz $@

# resyncMates
ifndef RESYNCMATES
RESYNCMATES=resyncMates.pl
endif
ifndef RESYNCMATES_OPTIONS
RESYNCMATES_OPTIONS=
endif

# Rule defined for read 1 only - execute if read 2 found
%$(READ1_LABEL).trimmed.sync.fastq.gz: %$(READ1_LABEL).trimmed.fastq.gz %$(READ2_LABEL).trimmed.fastq.gz
	$(RESYNCMATES) $(RESYNCMATES_OPTIONS) -i $< -j $*$(READ2_LABEL).trimmed.fastq.gz -o $@.tmp.gz -p $*$(READ2_LABEL).trimmed.sync.fastq.gz && mv $@.tmp.gz $@

# Needed since %$(READ2_LABEL).trimmed.sync.fastq.gz is a prerequisite for alignment
%$(READ2_LABEL).trimmed.sync.fastq.gz: %$(READ1_LABEL).trimmed.sync.fastq.gz
	@echo $@ should be done in rule 1


##############################
# Trimmomatic
##############################
ifndef TRIMMOMATIC_HOME
TRIMMOMATIC_HOME=.
endif
ifndef TRIMMOMATIC_OPTION_THREADS
TRIMMOMATIC_OPTION_THREADS=$(THREADS)
endif
ifndef TRIMMOMATIC_OPTIONS
TRIMMOMATIC_OPTIONS=-phred33 -threads $(TRIMMOMATIC_OPTION_THREADS)
endif
ifndef TRIMMOMATIC_PROCESSING_OPTIONS
TRIMMOMATIC_PROCESSING_OPTIONS=LEADING:15 TRAILING:15 MINLEN:36
endif

ifndef TRIMMOMATIC_JAVA_MEM
TRIMMOMATIC_JAVA_MEM=$(JAVA_MEM)
endif
ifndef TRIMMOMATIC_JAR
TRIMMOMATIC_JAR=$(TRIMMOMATIC_HOME)/trimmomatic.jar
endif
ifndef TRIMMOMATIC_JAVA_TMPDIR
TRIMMOMATIC_JAVA_TMPDIR=$(JAVA_TMPDIR)
endif
ifndef TRIMMOMATIC_COMMAND
TRIMMOMATIC_COMMAND=java -Xmx$(TRIMMOMATIC_JAVA_MEM) -Djava.io.tmpdir=$(TRIMMOMATIC_JAVA_TMPDIR) -jar $(TRIMMOMATIC_JAR)
endif

%.trimmomatic.PE: %$(READ1_LABEL).fq.gz %$(READ2_LABEL).fq.gz 
	$(TRIMMOMATIC_COMMAND) PE $(TRIMMOMATIC_OPTIONS) $^ $*$(READ1_LABEL).P.qtrim.fq.tmp.gz $*$(READ1_LABEL).U.qtrim.fq.tmp.gz $*$(READ2_LABEL).P.qtrim.fq.tmp.gz $*$(READ2_LABEL).U.qtrim.fq.tmp.gz $(TRIMMOMATIC_PROCESSING_OPTIONS) &> $@.tmp && mv $@.tmp $@ && mv $*$(READ1_LABEL).P.qtrim.fq.tmp.gz $*$(READ1_LABEL).P.qtrim.fq.gz && mv $*$(READ1_LABEL).U.qtrim.fq.tmp.gz $*$(READ1_LABEL).U.qtrim.fq.gz && mv $*$(READ2_LABEL).P.qtrim.fq.tmp.gz $*$(READ2_LABEL).P.qtrim.fq.gz && mv $*$(READ2_LABEL).U.qtrim.fq.tmp.gz $*$(READ2_LABEL).U.qtrim.fq.gz

%$(READ1_LABEL).P.qtrim.fq.gz: %.trimmomatic.PE
	echo Running rule $*.trimmomatic.PE to generate $@

%$(READ1_LABEL).U.qtrim.fq.gz: %.trimmomatic.PE
	echo Running rule $*.trimmomatic.PE to generate $@

%$(READ2_LABEL).P.qtrim.fq.gz: %.trimmomatic.PE
	echo Running rule $*.trimmomatic.PE to generate $@

%$(READ2_LABEL).U.qtrim.fq.gz: %.trimmomatic.PE
	echo Running rule $*.trimmomatic.PE to generate $@

##############################
# settings
##############################
.PRECIOUS: %.trimmomatic.PE
.PHONY: sequenceprocessing-settings sequenceprocessing-header

print-%:
	@echo '$*=$($*)'

sequenceprocessing-header:
	@echo -e "\nMakefile.sequenceprocessing options"
	@echo "==================================="


sequenceprocessing-settings: sequenceprocessing-header print-CUTADAPT print-CUTADAPT_THREEPRIME print-CUTADAPT_FIVEPRIME print-CUTADAPT_OPTIONS print-RESYNCMATES print-RESYNCMATES_OPTIONS
