#-*- makefile -*-

# General rules

# Utility programs
ifndef AWK
AWK=awk
endif
ifndef CAT
CAT=cat
endif
ifndef ZCAT
ZCAT=zcat
endif
ifndef GREP
GREP=grep
endif
ifndef GZIP
GZIP=gzip
GZIP_OPTIONS=
endif



##############################
# sbatch submission
##############################
ifndef SBATCH
SBATCH=sbatch
endif
ifndef SBATCH_OPTIONS
SBATCH_OPTIONS=
endif

##############################
# SLURM options
##############################
# SLURM account empty - required in calling Makefile
ifndef SLURM_ACCOUNT
SLURM_ACCOUNT=
endif
# SLURM time - 1h default
ifndef SLURM_TIME
SLURM_TIME=01:00:00
endif
# SLURM N nodes
ifndef SLURM_N_NODES
SLURM_N_NODES=1
endif
# Extra header info. Put everything in variable.
ifndef SLURM_EXTRA_HEADER
SLURM_EXTRA_HEADER=
endif
# Stuff to be inserted before command
ifndef SLURM_PREHOOK
SLURM_PREHOOK=
#="module load samtools\n\
#module load bwa\n\
#"
endif

# Jobname variable
ifndef SLURM_JOBNAME
SLURM_JOBNAME=
endif
# Workdir variable
ifndef SLURM_WORKDIR
SLURM_WORKDIR=
endif

# Mailtype variable
ifndef SLURM_MAILTYPE
SLURM_MAILTYPE=All
endif
# Mailuser variable
ifndef SLURM_PARTITION
SLURM_PARTITION=devel
endif
# Partition
ifndef SLURM_MAILUSER
SLURM_MAILUSER=
endif
# SLURM n cores
ifndef SLURM_N_CORES
SLURM_N_CORES=8
ifeq ($(SLURM_PARTITION),core)
SLURM_N_CORES=1
endif
endif


%.sbatch:
ifeq ($(SLURM_ACCOUNT),)
	echo -e No SLURM_ACCOUNT defined; exiting!
else
	echo -e "#!/bin/bash -l" > $@ 
	echo -e "#SBATCH" -p $(SLURM_PARTITION) >> $@ 
ifeq ($(SLURM_PARTITION),halvan)
	echo -e "#SBATCH" -M $(SLURM_PARTITION) >> $@
endif
	echo -e "#SBATCH" -A $(SLURM_ACCOUNT) >> $@ 
	echo -e "#SBATCH" -n $(SLURM_N_CORES) >> $@ 
ifeq ($(SLURM_PARTITION),node)
	echo -e "#SBATCH" -N $(SLURM_N_NODES) >> $@ 
endif
	echo -e "#SBATCH" -t $(SLURM_TIME) >> $@ 
ifneq ($(SLURM_JOBNAME),)
	echo -e "#SBATCH" -J $(SLURM_JOBNAME) >> $@ 
else
	echo -e "#SBATCH" -J $* >> $@ 
endif
ifneq ($(SLURM_WORKDIR),)
	echo -e "#SBATCH" -D $(SLURM_WORKDIR) >> $@
endif
ifneq ($(SLURM_EXTRA_HEADER),)
	echo -e $(SLURM_EXTRA_HEADER) >> $@ 
endif
	echo -e "#SBATCH --mail-type="$(SLURM_MAILTYPE) >> $@
ifneq ($(SLURM_MAILUSER),)
	echo -e "#SBATCH --mail-user="$(SLURM_MAILUSER) >> $@
endif
	echo -e "\n\n#" `date` >> $@ 
	echo -e "\n\n"$(SLURM_PREHOOK) >> $@
	echo -e $(MAKE) $*.log >> $@
	$(SBATCH) $(SBATCH_OPTIONS) $@
endif

# logging - output suffix = .runlog so this rule is always run
%.log:
	echo -e "\n\n"`date`"\n\n" >> $@.tmp
	$(MAKE) $(MFLAGS) $* 2>&1 | tee -a $@.tmp && mv $@.tmp $*.runlog


# Want %.log to run every time but this doesn't help?!?
.PHONY: general-settings general-header

# http://blog.melski.net/2010/11/30/makefile-hacks-print-the-value-of-any-variable/
print-%:
	@echo '$*=$($*)'

general-header:
	@echo -e "\nMakefile.general options"
	@echo "========================"

general-settings: general-header print-AWK print-CAT print-ZCAT print-GREP print-GZIP print-GZIP_OPTIONS print-SBATCH print-SBATCH_OPTIONS print-SLURM_PARTITION print-SLURM_N_CORES print-SLURM_N_NODES print-SLURM_ACCOUNT print-SLURM_WORKDIR print-SLURM_MAILUSER print-SLURM_MAILTYPE print-SLURM_TIME print-SLURM_JOBNAME print-SLURM_EXTRA_HEADER
