#-*- makefile -*-

#
# samtools makefile rules
# 

MAKEDIR = $(dir $(lastword $(MAKEFILE_LIST)))
ifeq ($(findstring Makefile.ngsvars,$(MAKEFILE_LIST)),)
include $(MAKEDIR)Makefile.ngsvars
endif

# samtools
ifndef SAMTOOLS
SAMTOOLS=samtools
endif
ifndef SAMTOOLS_THREADS
SAMTOOLS_THREADS=$(THREADS)
endif
ifndef SAMTOOLS_OPTIONS
SAMTOOLS_OPTIONS=
endif
ifndef SAMTOOLS_REF
SAMTOOLS_REF=$(REF)
endif

%.bam: %.sam
	$(SAMTOOLS) view -Sbh - > $@.tmp && mv $@.tmp $@


##############################
# settings
##############################
.PHONY: samtools-settings samtools-header

print-%:
	@echo '$*=$($*)'

samtools-header:
	@echo -e "\nMakefile.samtools options"
	@echo "========================="


samtools-settings: samtools-header print-SAMTOOLS print-SAMTOOLS_THREADS print-SAMTOOLS_OPTIONS print-SAMTOOLS_REF
