#-*- makefile -*-

MAKEDIR = $(dir $(lastword $(MAKEFILE_LIST)))
include $(MAKEDIR)/Makefile.ngsvars

# Angsd search path. Since some of the programs are located in the
# misc subfolder, use absolute search path. The user must set this
# variable in the makefile that includes this file, or else set the
# executable variables below.
ifndef ANGSD_PATH
ANGSD_PATH=.
endif

# Angsd executable
ifndef ANGSD
ANGSD=$(ANGSD_PATH)/angsd
endif
# emoptim executable
ifndef EMOPTIM
EMOPTIM=$(ANGSD_PATH)/misc/emOptim
endif
# emoptim2 executable
ifndef ANGSD_EMOPTIM2
ANGSD_EMOPTIM2=$(ANGSD_PATH)/misc/emOptim2
endif
# optimSFS executable
ifndef ANGSD_OPTIMSFS
ANGSD_OPTIMSFS=$(ANGSD_PATH)/misc/optimSFS
endif
# bgid executable
ifndef ANGSD_BGID
ANGSD_BGID=$(ANGSD_PATH)/misc/bgid
endif
# calcstat executable
ifndef ANGSD_CALCSTAT
ANGSD_CALCSTAT=$(ANGSD_PATH)/misc/calcStat
endif
ifndef ANGSD_OPTION_THREADS
ANGSD_OPTION_THREADS=$(THREADS)
endif
##############################
# Program options
##############################
# GL option - use GATK model by default
ifndef ANGSD_OPTION_GL
ANGSD_OPTION_GL=2
endif
# Maf option - use option 10 by default (EM unknown + EM known minor)
ifndef ANGSD_OPTION_MAF
ANGSD_OPTION_MAF=10
endif
# MajorMinor - 5 default (major is ancestral, minor inferred from Genotype Likelihoods)
#
# NB: if the ancestral is not in the inferred (major/minor) tuple, the
# site is discarded
ifndef ANGSD_OPTION_MAJORMINOR
ANGSD_OPTION_MAJORMINOR=5
endif
# Option realsfs
ifndef ANGSD_OPTION_REALSFS
ANGSD_OPTION_REALSFS=1
endif
# Ancestral file
# Set to empty here; will throw error
ifndef ANGSD_OPTION_ANC
ANGSD_OPTION_ANC=$(REF)
endif

# Window sizes and steps for thetas calculations
ifndef ANGSD_OPTION_WINDOW
ANGSD_OPTION_WINDOW=50000
endif

ifndef ANGSD_OPTION_STEP
ANGSD_OPTION_STEP=50000
endif

ifndef ANGSD_OPTION_MAXITER
ANGSD_OPTION_MAXITER=100
endif

ifndef ANGSD_OPTION_NCHR
ANGSD_OPTION_NCHR=
endif

# Precious files
.PRECIOUS: %.em.ml %.em2.ml %_full.list %.list

# Create SFS file
#
# Requirement: here a bam list text file (i.e. names and locations of
# bam files for population)
ifndef ANGSD_REALSFS_OPTIONS
ANGSD_REALSFS_OPTIONS=-realSFS 1 -GL $(ANGSD_OPTION_GL) -anc $(ANGSD_OPTION_ANC) -nThreads $(ANGSD_OPTION_THREADS)
endif
%.sfs: %.list
	$(ANGSD) $(ANGSD_REALSFS_OPTIONS) -bam $< -out $(@:.sfs=).tmp && mv $(@:.sfs=).tmp.sfs $@

# Several rules for generating ML-estimate of sfs. Need to set a sfs optimization program variable
# 1. emOptim2
ifndef ANGSD_EMOPTIM2_OPTIONS
ANGSD_EMOPTIM2_OPTIONS=-maxIter $(ANGSD_OPTION_MAXITER) -P $(ANGSD_OPTION_THREADS)
ifdef ANGSD_OPTION_TOLE
ANGSD_EMOPTIM2_OPTIONS+=-tole $(ANGSD_OPTION_TOLE)
endif
ifdef ANGSD_OPTION_SITES
ANGSD_EMOPTIM2_OPTIONS+=-nSites $(ANGSD_OPTION_SITES)
endif
endif
%.sfs.em2.ml: %.sfs
	$(ANGSD_EMOPTIM2) $< $(ANGSD_OPTION_NCHR) $(ANGSD_EMOPTIM2_OPTIONS) > $@.tmp && mv $@.tmp $@

# 2. emOptim
ifndef ANGSD_EMOPTIM_OPTIONS
ANGSD_EMOPTIM_OPTIONS=-maxIter $(ANGSD_OPTION_MAXITER)
endif
%.sfs.em.ml: %.sfs
	$(ANGSD_EMOPTIM) -binput $< -nChr $(ANGSD_OPTION_NCHR) $(ANGSD_EMOPTIM_OPTIONS) > $@.tmp && mv $@.tmp $@

# 3. optimSFS
ifdef ANGSD_OPTIMSFS_OPTIONS
ANGSD_OPTIMSFS_OPTIONS=
endif
%.sfs.ml: %.sfs
	$(ANGSD_OPTIMSFS) -binput $< -nChr $(ANGSD_OPTION_NCH) -outnames $@.tmp && mv $@.tmp $@

# doThetas
# Generate thetas files
ifndef ANGSD_DOTHETAS_OPTIONS
ANGSD_DOTHETAS_OPTIONS=-realSFS 1 -GL $(ANGSD_OPTION_GL) -anc $(ANGSD_OPTION_ANC) -doThetas 1 -nThreads $(ANGSD_OPTION_THREADS)
ifdef ANGSD_OPTION_CHR
ANGSD_DOTHETAS_OPTIONS+=-r $(ANGSD_OPTION_CHR)
endif
endif

%_$(ANGSD_OPTION_CHR).thetas.gz: %.sfs.em.ml %.list
	$(ANGSD) $(ANGSD_DOTHETAS_OPTIONS) -pest $< -bam $*.list -out $(@:.thetas.gz=).tmp && rename $(@:.thetas.gz=).tmp $(@:.thetas.gz=) $(@:.thetas.gz=).tmp*

%.thetas.gz: %.sfs.em.ml
	$(ANGSD) $(ANGSD_DOTHETAS_OPTIONS) -pest $< -bam $*.list -out $(@:.thetas.gz=).tmp && mv $@.tmp.thetas.gz $@

%.thetas.gz: %.sfs.em2.ml
	$(ANGSD) $(ANGSD_DOTHETAS_OPTIONS) -pest $< -bam $*.list -out $(@:.thetas.gz=).tmp && mv $@.tmp.thetas.gz $@


# doMafs
ifndef ANGSD_DOMAFS_OPTIONS
ANGSD_DOMAFS_OPTIONS=-anc $(ANGSD_OPTION_ANC) -doMajorMinor $(ANGSD_OPTION_MAJORMINOR) -doMaf $(ANGSD_OPTION_MAF) -GL $(ANGSD_OPTION_GL) -nThreads $(ANGSD_OPTION_THREADS)
endif
%.mafs.gz: %.list
	$(ANGSD) $(ANGSD_DOMAFS_OPTIONS) -bam $< -out $(@:.mafs.gz=).tmp && rename $(@:.mafs.gz=).tmp $(@:.mafs.gz=) $(@:.mafs.gz=).tmp*

# doCounts: Generate mpileup from show options
ifndef ANGSD_DOCOUNTS_OPTIONS
ANGSD_DOCOUNTS_OPTIONS=-doCounts 1 -dumpCounts 2 -anc $(ANGSD_OPTION_ANC)
endif
%.counts.gz: %.list
	$(ANGSD) $(ANGSD_DOCOUNTS_OPTIONS) -bam $< -out $(@:.sfs=.counts.gz).tmp && rename $(@:.counts.gz=).tmp $(@:.counts.gz=) $(@:.counts.gz=).tmp*

# add -show to get mpileup
%.mpileup: %.list
	$(ANGSD) $(ANGSD_DOCOUNTS_OPTIONS) -show 1 -bam $< -out $(@:.sfs=.mpileup).tmp && mv $(@:.mpileup=).tmp.mpileup $@ 

# bgid
%.thetas.gz.bin: %.thetas.gz
	$(BGID) make_bed $<

ifndef ANGSD_BGID_DOSTAT_OPTIONS
ANGSD_BGID_DOSTAT_OPTIONS=-step $(ANGSD_OPTION_STEP) -win $(ANGSD_OPTION_WINDOW) -nChr $(ANGSD_OPTION_NCHR)
endif
%.thetas.gz.bgid_pestPG: %.thetas.gz %.thetas.gz.bin
	$(BGID) do_stat $< $(ANGSD_BGID_DOSTAT_OPTIONS)


##############################
# ngsTools
##############################

ifndef NGSTOOLS_PATH
NGSTOOLS_PATH=.
endif
ifndef NGSFST
NGSFST=$(NGSTOOLS_PATH)/ngsFST
endif

##############################
# GEM
##############################
ifndef GEM_PATH
GEM_PATH=.
endif

# This is needed as GEM internally calls GEM programs
export PATH := $(GEM_PATH):$(PATH)

ifndef GEM_INDEXER_OPTIONS
GEM_INDEXER_OPTIONS=-T 7
endif
%.gem: %.fasta
	$(GEM_PATH)/gem-indexer $(GEM_INDEXER_OPTIONS) -i $< -o $*.tmp && mv $*.tmp.gem $@; mv $*.tmp.log $*.log

ifndef GEM_MAPPABILITY_OPTIONS
GEM_MAPPABILITY_OPTIONS=-l 100 -T 7
endif
%.mappability: %.gem
	$(GEM_PATH)/gem-mappability $(GEM_MAPPABILITY_OPTIONS) -I $< -o $*.tmp && mv $*.tmp.mappability $@
