#-*- makefile -*-

#
# picard makefile rules
# 

MAKEDIR = $(dir $(lastword $(MAKEFILE_LIST)))
ifeq ($(findstring Makefile.ngsvars,$(MAKEFILE_LIST)),)
include $(MAKEDIR)Makefile.ngsvars
endif

.PRECIOUS: %.bai

# PICARD_HOME variable
ifndef PICARD_HOME
PICARD_HOME=.
endif
ifndef PICARD_JAVA_MEM
PICARD_JAVA_MEM=$(JAVA_MEM)
endif
ifndef PICARD_JAVA_TMPDIR
PICARD_JAVA_TMPDIR=$(JAVA_TMPDIR)
endif
ifndef PICARD_JAVA
PICARD_JAVA=java -Xmx$(PICARD_JAVA_MEM) -Djava.io.tmpdir=$(PICARD_JAVA_TMPDIR) -jar 
endif
ifndef PICARD_REF
PICARD_REF=$(REF)
endif

# Common options
ifndef PICARD_OPTIONS_COMMON
PICARD_OPTIONS_COMMON=VALIDATION_STRINGENCY=SILENT
endif
ifndef PICARD_OPTIONS
PICARD_OPTIONS=$(PICARD_OPTIONS_COMMON)
endif

# Bam index
%.bai: %.bam
	$(PICARD_JAVA) $(PICARD_HOME)/BuildBamIndex.jar I=$< O=$@.tmp $(PICARD_OPTIONS) && mv $@.tmp $@

ifndef PICARD_OPTION_SORTSAM
PICARD_OPTION_SORTSAM=SORT_ORDER=coordinate
endif
%.sort.bam: %.bam
	$(PICARD_JAVA) $(PICARD_HOME)/SortSam.jar I=$< O=$@.tmp $(PICARD_OPTIONS) $(PICARD_OPTION_SORTSAM) && mv $@.tmp $@

%.dup.bam: %.bam
	$(PICARD_JAVA) $(PICARD_HOME)/MarkDuplicates.jar I=$< O=$@.tmp $(PICARD_OPTIONS) M=$(@:.bam=).dup_metrics && mv $@.tmp $@

%.interval_list: $(PICARD_REF)
	$(PICARD_JAVA) $(PICARD_HOME)/CreateSequenceDictionary.jar R=$< O=$@.tmp && mv $@.tmp $@

%.interval_list: %.bed $(subst .fa,.interval_list,$(PICARD_REF))
	$(CAT) $(lastword $^) > $@.tmp
	$(AWK) '{printf("%s\t%s\t%s\t%s\t%s\n", $$1,$$2,$$3,"+",$$4)}' $< >> $@.tmp && mv $@.tmp $@

# Metrics calculations
%.insert_metrics: %.bam
	$(PICARD_JAVA) $(PICARD_HOME)/CollectInsertSizeMetrics.jar H=$*.hist I=$< O=$@.tmp R=$(PICARD_REF) && mv $@.tmp $@

# Add read group information
%.rg.bam: %.bam
	java -Xmx2g -jar $(PICARD_HOME)/AddOrReplaceReadGroups.jar INPUT=$< OUTPUT=$@.tmp SORT_ORDER=coordinate \
	RGID=$(firstword $(subst ., ,$*)) RGLB=lib RGPL=ILLUMINA RGPU=$(firstword $(subst ., ,$*)) \
	RGSM=$(firstword $(subst /, ,$(firstword $(subst ., ,$*)))) CREATE_INDEX=true && mv $@.tmp $@; mv $@.tmp.bai $(@.bam=).bai

##############################
# Merging
# Difficult to write generic rules
##############################
ifndef PICARD_MERGESAM_OPTIONS
PICARD_MERGESAM_OPTIONS=CREATE_INDEX=true
endif
ifndef PICARD_MERGESAM_TARGETS
PICARD_MERGESAM_TARGETS=
endif

%.merge.bam: $(PICARD_MERGESAM_TARGETS)
	@$(eval INPUTFILES=$(addprefix INPUT=,$(filter $(dir $*)%, $(PICARD_MERGESAM_TARGETS))))
	$(PICARD_JAVA) $(PICARD_HOME)/MergeSamFiles.jar $(INPUTFILES) O=$@.tmp $(PICARD_OPTIONS_COMMON) $(PICARD_MERGESAM_OPTION) && mv $@.tmp $@ && mv $@.tmp.bai $(@:.bam=).bai



##############################
# settings
##############################
.PHONY: picard-settings picard-header

print-%:
	@echo '$*=$($*)'

picard-header:
	@echo -e "\nMakefile.picard options"
	@echo "======================="

picard-settings: picard-header print-PICARD_HOME print-PICARD_JAVA_MEM print-PICARD_JAVA_TMPDIR print-PICARD_JAVA print-PICARD_REF print-PICARD_OPTIONS_COMMON print-PICARD_SORTSAM_OPTIONS print-PICARD_MERGESAM_OPTIONS print-PICARD_MERGESAM_TARGETS
