#!/usr/bin/make -rRf
#-*- makefile -*-

#
# samtools makefile rules
# 

.PHONY: samtools-header samtools-settings
.DELETE_ON_ERROR:
.SECONDARY:

MAKEDIR = $(dir $(lastword $(MAKEFILE_LIST)))
ifeq ($(findstring Makefile.ngsvars,$(MAKEFILE_LIST)),)
include $(MAKEDIR)Makefile.ngsvars
endif

# samtools
ifndef SAMTOOLS
SAMTOOLS=samtools
endif
ifndef SAMTOOLS_THREADS
SAMTOOLS_THREADS=$(THREADS)
endif
ifndef SAMTOOLS_OPTIONS
SAMTOOLS_OPTIONS=
endif
ifndef SAMTOOLS_REF
SAMTOOLS_REF=$(REF)
endif

# Index a FASTA file
%.fa.fai: %.fa
	$(SAMTOOLS) faidx $<

# Convert a SAM file to a BAM file
%.bam: %.sam
	$(SAMTOOLS) view -Sb - > $@.tmp && mv $@.tmp $@

# Convert a BAM file to a SAM file
%.bam.sam: %.bam
	$(SAMTOOLS) view -h $< >$@

# Sort a SAM file and create a BAM file
%.sort.bam: %.sam
	$(SAMTOOLS) view -Su $< |$(SAMTOOLS) sort - $*.sort

# Sort a BAM file
%.sort.bam: %.bam
	$(SAMTOOLS) sort $< $*.sort

# Sort a BAM file by query name
%.qsort.bam: %.bam
	$(SAMTOOLS) sort -no $< - >$@

# Index a BAM file
%.bam.bai: %.bam
	$(SAMTOOLS) index $<

# Fix the mate pair information of a BAM file
%.fixmate.bam: %.qsort.bam
	$(SAMTOOLS) fixmate $< $@

# Remove duplicates from a BAM file
%.rmdup.bam: %.bam
	$(SAMTOOLS) rmdup $< $@

# Count flags of a BAM file
%.flagstat: %.bam
	$(SAMTOOLS) flagstat $< >$@

# Report BAM index stats
%.idxstats.tsv: %.bam %.bam.bai
	(printf 'tid\tlength\tnumMapped\tnumUnmapped\n' \
		&& $(SAMTOOLS) idxstats $<) >$@

##############################
# settings
##############################
.PHONY: samtools-settings samtools-header

print-%:
	@echo '$*=$($*)'

samtools-header:
	@echo -e "\nMakefile.samtools options"
	@echo "========================="


samtools-settings: samtools-header print-SAMTOOLS print-SAMTOOLS_THREADS print-SAMTOOLS_OPTIONS print-SAMTOOLS_REF
