#-*- makefile -*-

#
# GATK makefile rules
# 

# http://blog.jgc.org/2007/01/what-makefile-am-i-in.html
MAKEDIR = $(dir $(lastword $(MAKEFILE_LIST)))
include $(MAKEDIR)/Makefile.ngsvars

# GATK_HOME variable
ifndef GATK_HOME
GATK_HOME=.
endif
ifndef GATK_JAVA_MEM
GATK_JAVA_MEM=$(JAVA_MEM)
endif
ifndef GATK_JAR
GATK_JAR=$(GATK_HOME)/GenomeAnalysisTK.jar
endif
ifndef GATK_JAVA_TMPDIR
GATK_JAVA_TMPDIR=.
endif
ifndef GATK_COMMAND
GATK_COMMAND=java -Xmx$(GATK_JAVA_MEM) -Djava.io.tmpdir=$(GATK_JAVA_TMPDIR) -jar $(GATK_JAR)
endif
ifndef GATK_REF
GATK_REF=$(REF)
endif
ifndef GATK_DBSNP
GATK_DBSNP=$(DBSNP)
endif
ifndef GATK_TARGET_REGIONS
GATK_TARGET_REGIONS=$(TARGET_REGIONS)
endif

# Generic program options
ifndef GATK_THREADS
GATK_THREADS=$(THREADS)
endif

ifndef GATK_UNIFIEDGENOTYPER_OPTIONS
GATK_UNIFIEDGENOTYPER_OPTIONS=-stand_call_conf 30.0 -stand_emit_conf 10.0  --downsample_to_coverage 30 --output_mode EMIT_VARIANTS_ONLY -glm BOTH -nt $(GATK_THREADS) -R $(GATK_REF)
ifneq ($(GATK_DBSNP), "")
GATK_UNIFIEDGENOTYPER_OPTIONS+=--dbsnp $(GATK_DBSNP)
endif
ifneq ($(GATK_TARGET_REGIONS), "")
GATK_UNIFIEDGENOTYPER_OPTIONS+=-L $(GATK_TARGET_REGIONS)
endif
endif

##############################
# Generic bam rules
# 
# The following rules have as requirement any bam file
##############################

# Read Backed Phasing
ifndef GATK_READBACKEDPHASING_OPTIONS
GATK_READBACKEDPHASING_OPTIONS=
endif
ifndef GATK_VCFSUFFIX
GATK_VCFSUFFIX=.vcf
endif
%.phased.vcf: %.bam %.bai
	$(GATK_COMMAND) -T ReadBackedPhasing $(GATK_READBACKEDPHASING_OPTIONS) -I $< --variant $*$(GATK_VCFSUFFIX) -R $(GATK_REF) > $@.tmp && mv $@.tmp $@

# Select snp variants
ifndef GATK_SELECTSNPVARIANTS_OPTIONS
GATK_SELECTSNPVARIANTS_OPTIONS=--selectTypeToInclude SNP
endif
%.snp.vcf: %.vcf
	$(GATK_COMMAND) -T SelectVariants $(GATK_SELECTSNPVARIANTS_OPTIONS) --variant $< --out $@.tmp -R $(GATK_REF) && mv $@.tmp $@

##############################
# Multi-sample variant calling
# 
# Requires a variable GATK_BAM_LIST that contains the bam file
# requirements
# Output names are specific
##############################
ifndef GATK_BAM_LIST
GATK_BAM_LIST:=
endif

all.vcf: $(GATK_BAM_LIST) $(subst .bam,.bai,$(GATK_BAM_LIST))
	$(GATK_COMMAND) -T UnifiedGenotyper $(GATK_UNIFIEDGENOTYPER_OPTIONS) $(addprefix -I , $(GATK_BAM_LIST)) -o $@.tmp && mv $@.tmp $@

all.phased.vcf: all.vcf $(GATK_BAM_LIST) $(subst .bam,.bai,$(GATK_BAM_LIST))
	$(GATK_COMMAND) -T ReadBackedPhasing $(GATK_READBACKEDPHASING_OPTIONS) $(addprefix -I , $(GATK_BAM_LIST)) --variant $< -R $(GATK_REF) -o $@.tmp && mv $@.tmp $@
