#-*- makefile -*-
#
# File: Makefile.sequenceprocessing
#
# Description: recipies for various sequence processing
#
MAKEDIR = $(dir $(lastword $(MAKEFILE_LIST)))
ifeq ($(findstring Makefile.ngsvars,$(MAKEFILE_LIST)),)
include $(MAKEDIR)Makefile.ngsvars
endif

##################################################
# Cutadapt and resyncmates
##################################################
# cutadapt
ifndef CUTADAPT
CUTADAPT=cutadapt
endif
ifndef CUTADAPT_THREEPRIME
CUTADAPT_THREEPRIME=AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC
endif
ifndef CUTADAPT_FIVEPRIME
CUTADAPT_FIVEPRIME=AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT
endif
ifndef CUTADAPT_OPTIONS
CUTADAPT_OPTIONS=
endif

%.trimmed.fastq.gz: %.fastq.gz
	$(if $(findstring $(READ1_LABEL).fastq.gz,$<),\
	$(CUTADAPT) $(CUTADAPT_OPTIONS) -a $(CUTADAPT_THREEPRIME) $< -o $(@:.gz=).tmp.gz > $*.cutadapt_metrics && mv $(@:.gz=).tmp.gz $@,\
	$(CUTADAPT) $(CUTADAPT_OPTIONS) -a $(CUTADAPT_FIVEPRIME) $< -o $(@:.gz=).tmp.gz > $*.cutadapt_metrics && mv $(@:.gz=).tmp.gz $@)

# resyncMates
ifndef RESYNCMATES
RESYNCMATES=resyncMates.pl
endif
ifndef RESYNCMATES_OPTIONS
RESYNCMATES_OPTIONS=
endif

# Rule defined for read 1 only - execute if read 2 found
%$(READ1_LABEL).trimmed.sync.fastq.gz: %$(READ1_LABEL).trimmed.fastq.gz %$(READ2_LABEL).trimmed.fastq.gz
	@$(eval READ2=$(lastword $^))
	@if [ -e $(READ2) ]; then \
	echo "$(RESYNCMATES) $(RESYNCMATES_OPTIONS) -i $< -j $(READ2) -o $@.tmp.gz -p $(subst $(READ1_LABEL),$(READ2_LABEL),$@) && mv $@.tmp.gz $@"; \
	$(RESYNCMATES) $(RESYNCMATES_OPTIONS) -i $< -j $(READ2) -o $@.tmp.gz -p $(subst $(READ1_LABEL),$(READ2_LABEL),$@) && mv $@.tmp.gz $@; \
	else \
	echo "No such file " $(READ2); \
	fi; 

# Needed since %$(READ2_LABEL).trimmed.sync.fastq.gz is a prerequisite for alignment
%$(READ2_LABEL).trimmed.sync.fastq.gz: %$(READ1_LABEL).trimmed.sync.fastq.gz
	@echo $@ should be done in rule 1

##############################
# settings
##############################
.PHONY: sequenceprocessing-settings sequenceprocessing-header

print-%:
	@echo '$*=$($*)'

sequenceprocessing-header:
	@echo -e "\nMakefile.sequenceprocessing options"
	@echo "==================================="


sequenceprocessing-settings: sequenceprocessing-header print-CUTADAPT print-CUTADAPT_THREEPRIME print-CUTADAPT_FIVEPRIME print-CUTADAPT_OPTIONS print-RESYNCMATES print-RESYNCMATES_OPTIONS
